version: '3.8'
services:
  ebweb:
    container_name: php-apache
    build:
        context: ./app/docker/
        dockerfile: Dockerfile
    depends_on:
        - db
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: ychet
        MYSQL_USER: admin
        MYSQL_PASSWORD: adminpassword
    ports:
        - "3306:3306"
